### ISSUE TITLE
RPi 4 boot issue

### ISSUE THREAD

**Issue by rpilab3k** [UbiquityRobotics/ubiquity_main#213] opened 2019-11-19 21:28 UTC
I cannot get the mot current image to boot on a RPi 4. It boots on a RPi 3 B+. Is there a work around or an ETA on when RPi 4 will be supported?

**Comment by rohbotics** [comment] 2019-11-19 23:44
You should track this thread for information on Pi4 support. https://forum.ubiquityrobotics.com/t/ros-image-on-raspberry-pi-4/326/28

In short, we can make it boot, but Wifi (specifically AP mode) is not really working yet.

**Comment by rohbotics** [comment] 2020-02-01 20:55
Closing this because it is a duplicate of #200

**Closed as completed by rohbotics** 2020-02-01 20:55 UTC
